<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'core\\' => array($baseDir . '/src/core'),
    'app\\' => array($baseDir . '/src/app'),
    'Whoops\\' => array($vendorDir . '/filp/whoops/src/Whoops'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
);
